### ISSUE TITLE
bug: get_who_mr & WHO database display diferent results

### ISSUE THREAD

**Issue by gloriamacia** [aphp/rgho#2]
I am looking for the female MR aged 44.25 years in Spain. 

This is what I get from running my code: 
<img width="857" alt="image" src="https://github.com/aphp/rgho/assets/17580456/82ce2b40-933e-4075-9b54-016f17e50776">

This is what I see in the UI: 
<img width="1108" alt="image" src="https://github.com/aphp/rgho/assets/17580456/bf8a82c8-99c7-4c6d-835f-48b5cfaf67a1">
Note that the latest data available is 2021, not 2019. In 2019 the death rate was 96.4 per 100.000 individuals. See my code for a reproducible example with a seed in case I am missing something on my side, else this seems to be a bug. 

```
devtools::install_github("aphp/rgho")
library(rgho)

set.seed(42)

# Create a vector of ages (random values between 12 and 75)
ages <- sample(12:75, 20, replace = TRUE)
# Create a vector of genders (random values of 0 or 1)
# 0 is considered male, 1 is considered female
genders <- sample(0:1, 20, replace = TRUE)
# Create the dataframe
patients <- data.frame(age = ages, gender = genders)
print(patients)

# Compute the mean age
mean_age <- mean(patients$age)
print(mean_age)
# Compute the percentage of females
percentage_female <- sum(patients$gender == 1) / nrow(patients) * 100
print(percentage_female)

# compute mortality rate for each gender
mr_fmle = get_who_mr(mean_age, sex="FMLE", country="ESP", local = FALSE)
print(mr_fmle)
mr_mle = get_who_mr(mean_age, sex="MLE", country="ESP", local = FALSE)
print(mr_mle)
```

**Comment by KZARCA** [comment]
Rgho uses the API, which returns a narrower age interval. That could be the reason.
